using DepRadar.Application.Ecosystems;
using Shouldly;
using Xunit;

namespace DepRadar.Domain.Tests.Ecosystems;

public sealed class NpmLockfileTests
{
    [Fact]
    public void Parses_v3_packages_including_nested_and_scoped_skipping_dev_and_links()
    {
        const string json = """
            {
              "name": "demo", "lockfileVersion": 3,
              "packages": {
                "": { "name": "demo", "dependencies": { "express": "^4.18.0" } },
                "node_modules/express": { "version": "4.18.2", "license": "MIT" },
                "node_modules/express/node_modules/debug": { "version": "2.6.9" },
                "node_modules/@scope/tool": { "version": "1.0.0" },
                "node_modules/jest": { "version": "29.0.0", "dev": true },
                "node_modules/local-lib": { "link": true }
              }
            }
            """;

        var locked = NpmLockfile.Parse(json);

        locked.ShouldBe(
        [
            new LockedPackage("express", "4.18.2"),
            new LockedPackage("debug", "2.6.9"),      // nested path → innermost name
            new LockedPackage("@scope/tool", "1.0.0"),
        ]);
    }

    [Fact]
    public void Invalid_json_throws_and_missing_packages_yields_empty()
    {
        Should.Throw<FormatException>(() => NpmLockfile.Parse("nope"));
        NpmLockfile.Parse("""{ "lockfileVersion": 3 }""").ShouldBeEmpty();
    }
}

public sealed class PyPiLockfileTests
{
    [Fact]
    public void Parses_poetry_and_uv_style_package_blocks()
    {
        const string toml = """
            # This file is automatically generated.
            [[package]]
            name = "requests"
            version = "2.19.1"
            description = "Python HTTP for Humans."

            [package.dependencies]
            urllib3 = ">=1.21.1,<1.24"

            [[package]]
            name = "Django"
            version = "4.1.0"

            [metadata]
            lock-version = "2.0"
            """;

        var locked = PyPiLockfile.Parse(toml);

        // Names come out PEP 503 canonicalized; nested tables don't leak values.
        locked.ShouldBe(
        [
            new LockedPackage("requests", "2.19.1"),
            new LockedPackage("django", "4.1.0"),
        ]);
    }

    [Fact]
    public void Content_without_package_blocks_yields_empty()
    {
        PyPiLockfile.Parse("[metadata]\nlock-version = \"2.0\"\n").ShouldBeEmpty();
    }
}
